#!/bin/sh -eu
# \curl -sSL https://raw.githubusercontent.com/yisizawa/rc/master/.config/install | sh
cd
git -C "${HOME}" init
cat << EOL > ~/.git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[branch "master"]
	remote = https://github.com/yisizawa/rc.git
	merge = refs/heads/master
[submodule ".vim/dein.vim"]
	url = https://github.com/Shougo/dein.vim
	active = true
[submodule ".config/yisizawa/zplug"]
	url = https://github.com/yisizawa/zplug
	active = true
EOL
rm -f .bash_profile
git -C "${HOME}" pull
git -C "${HOME}" submodule update
cat << EOL > ~/.git/modules/.vim/dein.vim/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/Shougo/dein.vim
	fetch = +refs/heads/master:refs/remotes/origin/master
[branch "master"]
	remote = origin
	merge = refs/heads/master
EOL
