#!/bin/sh -eu
cd
git -C "${HOME}" init
cat << EOL > ~/.git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[branch "master"]
	remote = github.com:yisizawa/rc.git
	merge = refs/heads/master
[submodule ".vim/dein.vim"]
	url = https://github.com/Shougo/dein.vim
	active = true
[submodule ".config/zsh/zplug"]
	url = https://github.com/zplug/zplug
	active = true
EOL
git -C "${HOME}" pull
git -C "${HOME}" submodule update
cat << EOL > ~/.git/modules/.vim/dein.vim/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/Shougo/dein.vim
	fetch = +refs/heads/master:refs/remotes/origin/master
[branch "master"]
	remote = origin
	merge = refs/heads/master
EOL
